# MIT License
# 
# Copyright (c) 2019 Thiago Alves
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
- name: "Check if {{ rm_action.destination }} exists on remote host"
  shell: "test -f {{ tool.install.path }}/{{ rm_action.destination }}"
  register: _action_dest_isfile
  changed_when: false
  ignore_errors: true

- name: "Normalize check value"
  set_fact:
    _action_dest_isfile: "{{ _action_dest_isfile.rc == 0 }}"

- name: "Remove file: {{ tool.install.path }}/{{ rm_action.destination }}"
  file:
    path: "{{ tool.install.path }}/{{ rm_action.destination }}"
    state: absent
  when: _action_dest_isfile

- name: "Check if {{ rm_action.destination }} exists on remote host"
  shell: "test -d {{ tool.install.path }}/{{ rm_action.destination }}"
  register: _action_dest_isdir
  changed_when: false
  ignore_errors: true

- name: "Normalize check value"
  set_fact:
    _action_dest_isdir: "{{ _action_dest_isdir.rc == 0 }}"

- name: "Remove files at {{ tool.install.path }}/{{ rm_action.destination }}"
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: "{{ tool.install.path }}/{{ rm_action.destination }}/{{ rm_action.source|basename }}"
  loop_control:
    label: "{{ rm_action.destination }}/{{ item|basename }}"
  when: _action_dest_isdir